package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"
	"kickexchange/trading-service/internal/assets"
	"kickexchange/trading-service/internal/engineclient"
	"kickexchange/trading-service/internal/graphql/generated"
	"kickexchange/trading-service/internal/graphql/model"
	"kickexchange/trading-service/internal/transfermarkt"
)

// SubmitMarketOrder is the resolver for the submitMarketOrder field.
func (r *mutationResolver) SubmitMarketOrder(ctx context.Context, assetID uint64, side model.Side, shares int) (*model.SubmitResult, error) {
	engineSide, err := toEngineSide(side)
	if err != nil {
		return nil, err
	}

	orderID := r.nextOrderID.Add(1)
	result, err := r.Engine.SubmitMarket(assetID, engineclient.NewMarketPayload{
		OrderID: orderID,
		Side:    engineSide,
		Shares:  int64(shares),
	})

	if result.Rejected != nil {
		reason := result.Rejected.Reason.String()
		return &model.SubmitResult{OrderID: orderID, Accepted: false, RejectReason: &reason}, nil
	}
	if err != nil {
		return nil, err
	}
	return &model.SubmitResult{OrderID: orderID, Accepted: true}, nil
}

// AddPlayer is the resolver for the addPlayer field. Admin-only in intent -
// no auth exists yet to enforce that, this mutation is unprotected for now.
func (r *mutationResolver) AddPlayer(ctx context.Context, externalID string) (*model.Asset, error) {
	profile, err := r.Transfer.GetPlayerProfile(ctx, externalID)
	if err != nil {
		return nil, err
	}

	initialPrice := float64(profile.MarketValue) / 1_000_000
	a, err := r.Assets.Create(ctx, externalID, toSymbol(profile.Name), profile.Name, initialPrice)
	if err != nil {
		if errors.Is(err, assets.ErrAlreadyExists) {
			return nil, fmt.Errorf("graphql: player %s is already in the market", externalID)
		}
		return nil, err
	}
	return toModelAsset(a), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (bool, error) {
	return true, nil
}

// Player is the resolver for the player field.
func (r *queryResolver) Player(ctx context.Context, assetID uint64) (*model.Asset, error) {
	a, err := r.Assets.GetByAssetID(ctx, assetID)
	if err != nil {
		if errors.Is(err, assets.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return toModelAsset(a), nil
}

// SearchAssets is the resolver for the searchAssets field. Only ever
// returns assets already in our own table, per query design - this is what
// makes home page search show tradable players only.
func (r *queryResolver) SearchAssets(ctx context.Context, query string) ([]*model.Asset, error) {
	list, err := r.Assets.Search(ctx, query)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Asset, len(list))
	for i, a := range list {
		out[i] = toModelAsset(a)
	}
	return out, nil
}

// PreviewPlayer is the resolver for the previewPlayer field. Numeric query
// is treated as a transfermarkt id (direct profile lookup); anything else
// searches by name and returns the top match.
func (r *queryResolver) PreviewPlayer(ctx context.Context, query string) (*model.PlayerPreview, error) {
	if isNumericID(query) {
		profile, err := r.Transfer.GetPlayerProfile(ctx, query)
		if err != nil {
			if errors.Is(err, transfermarkt.ErrPlayerNotFound) {
				return nil, nil
			}
			return nil, err
		}
		return toModelPlayerPreview(profile), nil
	}

	results, err := r.Transfer.SearchPlayers(ctx, query)
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return nil, nil
	}
	return toModelPlayerPreview(results[0]), nil
}

// PlayerProfile is the resolver for the playerProfile field. Transfers are
// best-effort - if they fail, we still return the core profile rather than
// failing the whole query.
func (r *queryResolver) PlayerProfile(ctx context.Context, externalID string) (*model.PlayerProfile, error) {
	full, err := r.Transfer.GetFullProfile(ctx, externalID)
	if err != nil {
		if errors.Is(err, transfermarkt.ErrPlayerNotFound) {
			return nil, nil
		}
		return nil, err
	}

	transfers, err := r.Transfer.GetTransfers(ctx, externalID)
	if err != nil {
		r.Log.Warn("failed to fetch transfers", "external_id", externalID, "error", err)
	}

	return toModelPlayerProfile(full, transfers), nil
}

// PriceUpdates is the resolver for the priceUpdates field.
func (r *subscriptionResolver) PriceUpdates(ctx context.Context, assetID uint64) (<-chan float64, error) {
	ch, unsubscribe := r.Feed.Subscribe(assetID)
	go func() {
		<-ctx.Done()
		unsubscribe()
	}()
	return ch, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
