name: kickexchange

services:
  matching-engine:
    build:
      context: ../../services/matching-engine
    container_name: matching-engine
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - exchange-network

  trading-service:
    build:
      context: ../../services/trading-service
    container_name: trading-service
    environment:
      - ENGINE_HOST=matching-engine
      - ENGINE_PORT=9000
    depends_on:
      - matching-engine
    restart: unless-stopped
    networks:
      - exchange-network

networks:
  exchange-network:
