// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Asset struct {
	AssetID      uint64  `json:"assetId"`
	ExternalID   string  `json:"externalId"`
	Symbol       string  `json:"symbol"`
	DisplayName  string  `json:"displayName"`
	InitialPrice float64 `json:"initialPrice"`
}

type Mutation struct {
}

type PlayerPreview struct {
	ExternalID  string `json:"externalId"`
	Name        string `json:"name"`
	MarketValue int    `json:"marketValue"`
}

type Query struct {
}

type SubmitResult struct {
	OrderID      uint64  `json:"orderId"`
	Accepted     bool    `json:"accepted"`
	RejectReason *string `json:"rejectReason,omitempty"`
}

type Subscription struct {
}

type Side string

const (
	SideBuy  Side = "BUY"
	SideSell Side = "SELL"
)

var AllSide = []Side{
	SideBuy,
	SideSell,
}

func (e Side) IsValid() bool {
	switch e {
	case SideBuy, SideSell:
		return true
	}
	return false
}

func (e Side) String() string {
	return string(e)
}

func (e *Side) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Side(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Side", str)
	}
	return nil
}

func (e Side) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Side) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Side) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
